name: 'PR Compliance Action'
description: 'Action to check PR compliance on various aspects'
author: 'Matthew Foley'
inputs:
  repo-token:
    required: true
    description: 'Repo Access Token'
    default: ''
  body-regex:
    required: true
    description: 'PR Body Regex'
    default: '(fix|clos|resolv)(es)* #\d+'
  ignore-authors:
    required: true
    description: >
      PR Authors to ignore (e.g. dependabot). All checks will be skipped and action outputs will be
      set to true if the PR has one of these authors.
    default: >
      dependabot
      dependabot[bot]
  body-auto-close:
    required: true
    description: 'Whether or not to auto-close on failed check of PR Body'
    default: true
  body-comment:
    required: true
    description: 'Comment to leave on PR on failed check of PR Body'
    default: >
      Thank you for your Pull Request! In order to be considered for merging,
      the pull request description must refer to a specific issue number. This
      is described in our Contributing Guide. We are closing this issue for now
      but you can update the pull request description and reopen it.
  protected-branch:
    required: true
    description: 'Protected Branch'
    default: ''
  protected-branch-auto-close:
    required: true
    description: Whether or not to auto-close on failed check of PR head branch'
    default: true
  protected-branch-comment:
    required: true
    description: 'Comment to leave on PR on failed check of PR head branch.'
    default: >
      Thank you for your Pull Request! In order to be considered for merging,
      the pull request description must not be from the "%branch%" branch. This
      is described in our Contributing Guide. We are closing this pull request
      and we would suggest that you implement your changes as described in our
      documents and open a new pull request.
  title-check-enable:
    required: true
    description: 'Whether or not to lint PR title per @commitlint/conventional-commit.'
    default: true
  title-comment: 
    required: true
    description: 'Comment to leave on PR on failed check of PR title per @commitlint/conventional-commit'
    default: >
      Thank you for your Pull Request! In order to be considered for merging,
      the pull request title must match the specification in 
      [@commitlint/conventional-commit](https://www.conventionalcommits.org/en/v1.0.0/).
  watch-files:
    required: true
    description: 'Files to flag modifications'
    default: ''
  watch-files-comment:
    required: true
    description: 'Comment to leave on PR when watched files have been changed.'
    default: >
      Thank you for your Pull Request! This pull request modifies specific files that require careful review.
outputs:
  body-check:
    description: 'Result of match for PR Body against configured regex.'
  branch-check:
    description: 'Result of check to ensure PR head is not protected branch.'
  title-check:
    description: 'Result of check to ensure PR title is formatted per @commitlint/conventional-commit'
  watch-files-check:
    description: 'Result of check for watched files having been modified. True if no modifications found to watched files.'
runs:
  using: 'node12'
  main: 'dist/index.js'
