name: 'PR Compliance Action'
description: 'Action to check PR compliance on various aspects'
author: 'Matthew Foley'
inputs:
  repo-token:
    required: true
    description: 'Repo Access Token'
    default: ''
  body-regex:
    required: true
    description: 'PR Body Regex'
    default: '(fix|clos|resolv)(es)* #\d+'
  body-ignore-authors:
    required: true
    description: 'Authors to ignore for PR body regex (e.g. dependabot[bot]'
    default: >
      dependabot
      dependabot[bot]
  body-auto-close:
    required: true
    description: 'Whether or not to auto-close on failed check of PR Body'
    default: true
  body-comment:
    required: true
    description: 'Comment to leave on PR on failed check of PR Body'
    default: >
      Thank you for your Pull Request! In order to be considered for merging,
      the pull request description must refer to a specific issue number. This
      is described in our Contributing Guide. We are closing this issue for now
      but you can update the pull request description and reopen it.
  protected-branch:
    required: true
    description: 'Protected Branch'
    default: ''
  protected-branch-auto-close:
    required: true
    description: Whether or not to auto-close on failed check of PR head branch'
    default: true
  protected-branch-comment:
    required: true
    description: 'Comment to leave on PR on failed check of PR head branch.'
    default: >
      Thank you for your Pull Request! In order to be considered for merging,
      the pull request description must not be from the "main" branch. This
      is described in our Contributing Guide. We are closing this pull request
      and we would suggest that you implement your changes as described in our
      documents and open a new pull request.
  watch-files:
    required: true
    description: 'Files to flag modifications'
    default: ''
outputs:
  body-check:
    description: 'Result of match for PR Body against configured regex.'
runs:
  using: 'node12'
  main: 'dist/index.js'
