name: 'PR Compliance Action'
description: 'Action to check PR compliance on various aspects'
author: 'Matthew Foley'
inputs:
  repo-token:
    required: true
    description: 'Repo Access Token'
    default: ''
  body-regex:
    required: true
    description: 'PR Body Regex'
    default: '(fix|clos|resolv)(es)* #\d+'
  protected-branch:
    required: true
    description: 'Protected Branch'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
